apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: petclinic-cluster
  region: us-east-1
  version: "1.28"
iam:
  serviceRoleARN: arn:aws:iam::753965154007:role/eksServiceRole
nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    volumeSize: 80
